### ISSUE TITLE
Clarify Docs / Workings of "Running Drippers"

### ISSUE THREAD

**Issue by jon-sully** [joshmn/caffeinate#27]
Working on some other stuff at the moment but wanted to write this down before I forgot!

I think we probably need stronger / clearer docs around getting the whole system "running". Someone can setup Drippers, subscribe things to them, and have all their Mailers in order, ship all that to prod, then wonder why stuff isn't sending. It's not super clear that they also need to setup a background job (or other system) to continuously "run" the drippers.

It would also be nice if there was a global "run all of them command". Right now I'm using 

```ruby
ApplicationDripper.descendants.each do |klass|
      klass.perform!
    end
```

But that could come out of the box with Caffeinate

**Comment by joshmn** [comment]
Pushed
