### ISSUE TITLE
Cool Project

### ISSUE THREAD

**Issue by chrisedington** [joshmn/caffeinate#3]
Not an issue, just nice to see the effort you've put into the project.

Thanks for the OS.

**Comment by joshmn** [comment]
hey thanks! it was much needed for one of my projects, and after seeing the cute-sy implementation of a drip campaign we had at work i knew there was at least a need for something :) 

feel free to touch base by email if you have any additional thoughts or questions or anything :)

**Comment by erozas** [comment]
I think the same. I'm not going to open another issue to thank you but it's a really cool project. I'm going to use it for an app I'm developing. Thanks for the effort!
